name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checkout and merge ppt to master
        run: 
            git fetch -p
            git branch
            git checkout master
            git merge ppt 
            git push
        shell: bash


      