name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: display info
        run: |
          pwd 
          ls --all
        shell: bash
      - name: simple action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: Magda
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
      