name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check git branches
        run: |
          git branch
          git fetch -p 
          git branch


      