name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd 
          ls --all
        shell: bash
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: list files after checkout
        run: |
          pwd 
          ls --all
          git branch

      