name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ppt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check current directory
        run: |
          pwd
          ls
      - name: clear metadata in ipynb files
        run: |
          print('something')
          import utilities
        shell: python
      - name: merge ppt into master
        run: |
          git branch
          git checkout master
          git merge ppt 
          git push


      