name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ppt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clear metadata in ipynb files
        run: |
          python clean_ipynb_files.py
      - name: commit cleared ipynb files and push to ppt
        run: |
          git add .
          git commit -m "clear ipynb metadata"
          git push
      - name: merge ppt into master
        run: |
          git checkout master
          git merge ppt 
          git push


      