name: "Deploy ppt to master"

on:
  push:
    branches:
      - ppt

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ppt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clear metadata in ipynb files
        run: |
          print('something')
          from utilities import get_files_with_extension, clear_notebook_metadata
          print(get_files_with_extension())
        shell: python
      - name: merge ppt into master
        run: |
          git branch
          git checkout master
          git merge ppt 
          git push


      