name: "Shell Commands"

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline commands
        run: |
          node -v
          npm -v
      - name: show info
        run: echo "I run step in the github actions workflow"
      - name: python commands
        run: |
          print('Some python command')
          print('I can use python in workflow')
        shell: python
      - name: define a variable
        run: |
          message = "I am a variable in a first job"
        shell: python
  run-python-command:
    runs-on: ubuntu-latest
    steps: 
      - name: define a variable
        run: |
          message = "I am a variable in a first job"
      - name: print a variable
        run: |
          print(message)
        shell: python

