name: "Shell Commands"

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline commands
        run: |
          node -v
          npm -v
      - name: show info
        run: echo "I run step in the github actions workflow"
      - name: python commands
        run: |
          print('Some python command')
          print('I can use python in workflow')
        shell: python
      - name: save text to file
        run: |
          echo "I am a content of a file in a second job" >> message.txt
        shell: bash
  run-python-command:
    runs-on: ubuntu-latest
    needs: "run-shell-command"
    steps: 
      - name: print a text file
        run: |
          with open('message.txt') as file:
            file_contents = file.read()
            print(file_contents)
        shell: python

